AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3]  # Image dimensions specific to our model
BATCH_SIZE: 32
INCLUDE_TOP: FALSE  # Exclude the top layer for transfer learning
EPOCHS: 200
CLASSES: 4
WEIGHTS: imagenet
LEARNING_RATE: 0.0005