artifacts_root: artifacts



data ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1sSjqm3f4v5j3A7hLT9qUvocvmcUq0Sdy/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion